### ISSUE TITLE
Compatibility with fastify 4.x.x

### ISSUE THREAD

**Issue by stearm** [nucleode/arecibo#7]
Is arecibo compatible with the latest version of Fastify? Seems like `^3.0.0 ^4.0.0` is not working. In this case, I would open a PR since I need it 😄

**UPDATE**: I can confirm that `^3.0.0 ^4.0.0` is not the correct format, `^3.0.0 || ^4.0.0` works fine, opening a PR.

**Comment by tehKapa** [comment]
Thanks for the PR!
